import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <h1 className="text-6xl">Bluemoji</h1>
          <h2>
            a silly free-time project by{" "}
            <a href="https://bsky.app/profile/aendra.com">@aendra.com</a>
          </h2>
          {children}
        </main>
      </body>
    </html>
  );
}
