-- This file is auto-generated by hatk on startup. Do not edit.
-- Database engine: sqlite

CREATE TABLE _cursor (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE _labels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  src TEXT NOT NULL,
  uri TEXT NOT NULL,
  val TEXT NOT NULL,
  neg INTEGER DEFAULT 0,
  cts TEXT NOT NULL,
  exp TEXT
);

CREATE TABLE _oauth_codes (
  code TEXT PRIMARY KEY,
  request_uri TEXT NOT NULL,
  created_at INTEGER NOT NULL
);

CREATE TABLE _oauth_dpop_jtis (
  jti TEXT PRIMARY KEY,
  expires_at INTEGER NOT NULL
);

CREATE TABLE _oauth_keys (
  kid TEXT PRIMARY KEY,
  private_key TEXT NOT NULL,
  public_key TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE _oauth_refresh_tokens (
  token TEXT PRIMARY KEY,
  client_id TEXT NOT NULL,
  did TEXT NOT NULL,
  dpop_jkt TEXT NOT NULL,
  scope TEXT,
  created_at INTEGER NOT NULL,
  expires_at INTEGER,
  revoked INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE _oauth_requests (
  request_uri TEXT PRIMARY KEY,
  client_id TEXT NOT NULL,
  redirect_uri TEXT NOT NULL,
  scope TEXT,
  state TEXT,
  code_challenge TEXT NOT NULL,
  code_challenge_method TEXT NOT NULL DEFAULT 'S256',
  dpop_jkt TEXT NOT NULL,
  pds_request_uri TEXT,
  pds_auth_server TEXT,
  pds_endpoint TEXT,
  pds_code_verifier TEXT,
  pds_state TEXT,
  did TEXT,
  login_hint TEXT,
  expires_at INTEGER NOT NULL
);

CREATE TABLE _oauth_sessions (
  did TEXT PRIMARY KEY,
  pds_endpoint TEXT NOT NULL,
  pds_auth_server TEXT,
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  dpop_jkt TEXT NOT NULL,
  token_expires_at INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE _preferences (
  did TEXT NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (did, key)
);

CREATE TABLE _push_tokens (
  did TEXT NOT NULL,
  token TEXT NOT NULL,
  platform TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (did, token)
);

CREATE TABLE _reports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  subject_uri TEXT NOT NULL,
  subject_did TEXT NOT NULL,
  label TEXT NOT NULL,
  reason TEXT,
  reported_by TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  resolved_by TEXT,
  resolved_at TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE _repos (
  did TEXT PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'pending',
  handle TEXT,
  backfilled_at TEXT,
  rev TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0,
  retry_after INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE "app.bsky.feed.postgate" (
  uri TEXT PRIMARY KEY,
  cid TEXT,
  did TEXT NOT NULL,
  indexed_at TEXT NOT NULL,
  post TEXT NOT NULL,
  created_at TEXT NOT NULL,
  embedding_rules TEXT,
  detached_embedding_uris TEXT
);

CREATE TABLE "app.bsky.feed.threadgate" (
  uri TEXT PRIMARY KEY,
  cid TEXT,
  did TEXT NOT NULL,
  indexed_at TEXT NOT NULL,
  post TEXT NOT NULL,
  allow TEXT,
  created_at TEXT NOT NULL,
  hidden_replies TEXT
);

CREATE TABLE "blue.moji.collection.item" (
  uri TEXT PRIMARY KEY,
  cid TEXT,
  did TEXT NOT NULL,
  indexed_at TEXT NOT NULL,
  name TEXT NOT NULL,
  alt TEXT,
  created_at TEXT NOT NULL,
  formats TEXT NOT NULL,
  adult_only INTEGER,
  labels TEXT,
  copy_of TEXT,
  fallback_text TEXT,
  "sticker_formats" TEXT
);

CREATE TABLE "blue.moji.collection.item__formats_formats_v0" (
  parent_uri TEXT NOT NULL,
  parent_did TEXT NOT NULL,
  original TEXT,
  png_128 TEXT,
  apng_128 TEXT,
  gif_128 TEXT,
  webp_128 TEXT,
  lottie TEXT
);

CREATE TABLE "blue.moji.collection.item__formats_formats_v1" (
  parent_uri TEXT NOT NULL,
  parent_did TEXT NOT NULL,
  original TEXT,
  png_128 TEXT,
  apng_128 TEXT,
  gif_128 TEXT,
  webp_128 TEXT,
  lottie TEXT
);

CREATE TABLE "blue.moji.collection.item__labels_self_labels" (
  parent_uri TEXT NOT NULL,
  parent_did TEXT NOT NULL,
  val TEXT
);

CREATE TABLE "blue.moji.collection.item__sticker_formats_sticker_formats_v0" (
  parent_uri TEXT NOT NULL,
  parent_did TEXT NOT NULL,
  png_512 TEXT,
  webp_512 TEXT,
  gif_512 TEXT,
  apng_512 TEXT,
  lottie TEXT
);

CREATE TABLE "blue.moji.feed.reaction" (
  uri TEXT PRIMARY KEY,
  cid TEXT,
  did TEXT NOT NULL,
  indexed_at TEXT NOT NULL,
  subject TEXT NOT NULL,
  subject_cid TEXT,
  emoji TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "blue.moji.packs.pack" (
  uri TEXT PRIMARY KEY,
  cid TEXT,
  did TEXT NOT NULL,
  indexed_at TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  description_facets TEXT,
  icon TEXT,
  adult_only INTEGER,
  created_at TEXT NOT NULL,
  labels TEXT
);

CREATE TABLE "blue.moji.packs.pack__labels_self_labels" (
  parent_uri TEXT NOT NULL,
  parent_did TEXT NOT NULL,
  val TEXT
);

CREATE TABLE "blue.moji.packs.packitem" (
  uri TEXT PRIMARY KEY,
  cid TEXT,
  did TEXT NOT NULL,
  indexed_at TEXT NOT NULL,
  subject TEXT NOT NULL,
  pack TEXT NOT NULL,
  created_at TEXT NOT NULL
);
